version: '3'
services:
  mongo:
    image: mongo
    env_file:
      - envs/.mongo.env
  mongo-express:
    image: mongo-express
    env_file:
      - envs/.mongo-express.env
    depends_on:
      - mongo
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
  backend-server:
    hostname: backendserver
    build:
      context: .
      dockerfile: ./backend-server/Dockerfile
    env_file:
      - envs/.backend-server.env
    depends_on:
      - mongo
    ports:
      - "${BACKEND_SERVER_GRPC_PORT}:50051"
  backend-api:
    hostname: backendapi
    build:
      context: .
      dockerfile: ./backend-api/Dockerfile
    env_file:
      - envs/.backend-api.env
    depends_on:
      - backend-server
    ports:
      - "${BACKEND_API_HTTP_PORT}:50052"